### PR TITLE
Add notations to phrases

### PR DESCRIPTION
**Pull request by owenjonesuob**
### Motivation

I was recently attempting to transcribe the bass guitar part for [this song](https://www.youtube.com/watch?v=DSK2ER81b48), and after noticing some repetition which I could use to my advantage, I wanted to add some "higher-level" notation to help the reader keep track of their position in the song. But I couldn't find a way of adding it besides modifying each phrase separately, to add a different label to the first note. I was hoping for something more like:

```r
buzz <- pc(
  notate(volta(riff), "Intro"),
  riff_end,
  notate(volta(verse), "Verse"),
  notate(volta(verse), "Chorus"),
  notate(breakdown, "Breakdown"),
  volta(riff),
  notate(volta(verse), "Chorus"),
  bridge_final,
  notate(riff_end, "Outro")
)
```

### Implementation

The `notate.phrase()` S3 method is introduced. It works in almost exactly the same way as `notate()`, but inserts `text` after the first note of a phrase `x`. Then `notate.default()` is the current implementation of `notate()`, with no changes at all. See `phrase_helpers.R` for full context.

```r
notate <- function(x, text, position = "top") {
  UseMethod("notate", x)
}

notate.default <- function(x, text, position = "top") {
  pos <- switch(position, top = "^", bottom = "_")
  paste0(x, ";", pos, "\"", gsub(" ", "_", text), "\"", collapse = " ")
}

notate.phrase <- function(x, text, position = "top") {
  pos <- switch(position, top = "^", bottom = "_")
  # Find first note in phrase, and append notation
  sub("(<\\S+>.)", paste0("\\1", pos, "\"", gsub(" ", "_", text), "\"", collapse = " "), x)
}
```

There are other ways this could be implemented of course. For a long time I couldn't decide whether to extend `notate()`, or to introduce a new function, `notate_phrase()` or similar. But I figured I might as well share what I have, in case it seems useful as a concept, and details can always be discussed later ☺️ many thanks for this fantastic package, I'm having a great time learning how to use it!

### CODE REVIEW

**Comment by leonawicz** [comment]
Hey, thanks for your submission. I took a quick look and on the surface the need is understandable and the generic method solution sounds like the way I'd want to do it in tabr. I'll have to take a closer look and consider it more broadly when I play around with it later. I have RStudio:conf coming up this week and things are bit busy. Just want to give you a heads up since this PR will be probably be left open for a while until I can give it the attention it deserves. Thanks!
Matt

**Comment by owenjonesuob** [comment]
Awesome, thanks for letting me know Matt, enjoy the conference!! Say hi for me if you spot anyone from Mango 😸

**Comment by leonawicz** [comment]
I'm still open to this capability, but there needs to be more edge case handling at least. Here are a couple things I found just now.

```
> notate(p("a b", "8"), "intro")
<Musical phrase>
<a>8^"intro" <b>8

> notate(p("ac'e' b", "8"), "intro")
<Musical phrase>
<a c' e'>8 <b>8^"intro"
```

```
> z <- as_music("c4 d e ceg", labels = "intro")
> z
<Music string>
  Format: space-delimited time
  Values: c4;^"intro" d4 e4 <ceg>4

> p(z)
<Musical phrase>
<c>4^"intro" <d>4 <e>4 <c e g>4

> notate(p(z), "intro")
<Musical phrase>
<c>4^"intro"^"intro" <d>4 <e>4 <c e g>4
```

It may not be the best idea to make too many assumptions about the structure of a phrase object. It's also encouraged (when possible) to use the more convenient form of music notation data entry, `as_music()`, which also allows notating any time step, instead of entering everything directly with `phrase()` using 2 or even 3 arguments.

Repeat section functions like `volta()` are convenient for what they do, but are going to cause some rigidity whenever used. As a result, I still see this as useful, but perhaps it needs to be more strict.

I'm still wondering if there is a better way to address the need here by improving functions like `volta()` while encouraging use of `as_music()`, rather than operating directly on already constructed phrases. I often get requests for hacking apart phrase objects and if there is any other way to avoid the need to do so, I aim for that. Ideally, once a phrase string containing lilypond syntax has been created, the user should be done with it and any further edits should be done directly in their lilypond file. I do like this feature but it's worth some time to consider more robust ways to provide it and avoid ad hoc phrase edits.

Thoughts?

**Comment by leonawicz** [comment]
There hasn't been any traction on this, but also it's just not striking me as the right approach to the issue you are facing (the edge case issues aside). These kinds of requests, while all a bit different, have come up several times and the recurring theme seems to be a desire to do ad hoc string manipulation on the LilyPond syntax output from `phrase()`.

Ultimately, I think this points to a need to offer something more useful earlier in the process, e.g. `as_music()`, or to export to .ly file and manually tweak to unique user needs. There are near infinite things users can do in LilyPond, so I think I will continue to get a lot of unique requests for what `phrase()` should do or how phrase output can be beaten into submission to take some other shape, but I just won't be able to support all the needs.

**Pull request closed without merging**
